### ISSUE TITLE
Repository guidelines violation

### ISSUE THREAD

**Issue by gmltA** [mrkomilfo/MyBlog#1]
I have no idea whose repo is it.

**Comment by mrkomilfo** [comment]
Добавил эту информацию в readme. Также сделал наиболее технически сложные компоненты (меню, список статей, полная статья, профиль пользователя, фильтр, пагинация, 404, модальные окна и некоторые другие). Остались только всевозможные формочки, но они все довольно однообразны и имеют тривиальную структуру. Также работают get запросы и авторизация. Пробую задеплоить всё это на Azure, но пока безуспешно. Сталкиваюсь с проблемой, не представляя даже как искать её причину.

**Comment by gmltA** [comment]
Вы ж ведаеце, што лабы трэба праз pull-requests здаваць? Інакш я іх і прыняць не здолею.
